#!/usr/bin/env bash
# Manual deployment instructions for D&D site
# Run these commands on your VPS after uploading files manually

echo "=========================================="
echo "Manual Deployment Guide"
echo "=========================================="
echo ""
echo "Since SSH key authentication isn't set up, follow these steps:"
echo ""
echo "STEP 1: Upload files using SCP with password"
echo "-------------------------------------------"
echo "On your LOCAL computer, run:"
echo ""
echo "  # Create directory on VPS first"
echo "  ssh stefan@caravanserai.gr"
echo "  (enter your password when prompted)"
echo "  sudo mkdir -p /var/www/dnd-site"
echo "  sudo chown \$USER:\$USER /var/www/dnd-site"
echo "  exit"
echo ""
echo "  # Then upload files"
echo "  scp -r ~/tabletop_games/D&D/dnd_site/* stefan@caravanserai.gr:/var/www/dnd-site/"
echo ""
echo "STEP 2: Set permissions on VPS"
echo "-------------------------------------------"
echo "SSH into your VPS:"
echo ""
echo "  ssh stefan@caravanserai.gr"
echo "  sudo chmod -R 755 /var/www/dnd-site"
echo ""
echo "STEP 3: Configure web server"
echo "-------------------------------------------"
echo ""
echo "Option A - Add to nexus365 Caddyfile:"
echo ""
echo "  cd ~/repositories/portfolio_projects/nexus365"
echo "  nano Caddyfile"
echo ""
echo "  Add this block:"
cat << 'EOF'

dnd.caravanserai.gr {
    root * /var/www/dnd-site
    file_server
    try_files {path} {path}/index.html =404
    encode gzip
}
EOF
echo ""
echo "  Then reload:"
echo "  docker compose restart caddy"
echo ""
echo "Option B - Standalone Docker:"
echo ""
echo "  cd /var/www/dnd-site"
echo "  docker compose -f docker-compose.standalone.yaml up -d"
echo ""
echo "=========================================="
echo "Alternative: Set up SSH Keys (Recommended)"
echo "=========================================="
echo ""
echo "Run these ONCE on your local computer:"
echo ""
echo "  # Generate key (press Enter for defaults)"
echo "  ssh-keygen -t ed25519 -C 'your-email@example.com'"
echo ""
echo "  # Copy to VPS (enter password when prompted)"
echo "  ssh-copy-id stefan@caravanserai.gr"
echo ""
echo "  # Test (should not ask for password)"
echo "  ssh stefan@caravanserai.gr"
echo ""
echo "After this, ./deploy.sh will work without passwords!"
echo ""
